name: Build armeabi-v7a libs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Download and setup Android NDK r27d
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip -O ndk.zip
          unzip ndk.zip
          export ANDROID_NDK_ROOT=$PWD/android-ndk-r27d
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Build with ndk-build
        run: |
          cd love/src/jni
          ndk-build APP_ABI=armeabi-v7a

      - name: blah
        run: |
          cd love/src/libs
          zip -r armeabi-v7a.zip armeabi-v7a

      - name: Upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: armeabi-v7a-libs
          path: love/src/libs/armeabi-v7a.zip
